<template><div><blockquote>
<p>本頁記錄整理個人常用的 CS2 控制台設定與快捷鍵綁定，便於日後備份與查閱。</p>
</blockquote>
<h2 id="顯示與-hud-設定" tabindex="-1"><a class="header-anchor" href="#顯示與-hud-設定"><span>顯示與 HUD 設定</span></a></h2>
<div class="language-cs line-numbers-mode" data-highlighter="shiki" data-ext="cs" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_teamid_overhead_mode</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 2</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">        // 顯示隊友頭上 ID（2 為箭頭、名稱和生命值）</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_hud_color</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 9</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">                   // HUD 顏色（9 為綠色）</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">r_player_visibility_mode</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">con_enable</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 1</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">                     // 啟用控制台</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">fps_max</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 300</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">                      // 限制最大 FPS</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="準星設定" tabindex="-1"><a class="header-anchor" href="#準星設定"><span>準星設定</span></a></h2>
<div class="language-cs line-numbers-mode" data-highlighter="shiki" data-ext="cs" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshairalpha</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 255</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshaircolor</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 5</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">              // 自訂顏色</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshaircolor_r</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshaircolor_g</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 255</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshaircolor_b</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshair_friendly_warning</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshairgap</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> -</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">2.4</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshairgap_useweaponvalue</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshair_recoil</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshairsize</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 2.5</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshairstyle</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 4</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshairthickness</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 1</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshairdot</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_crosshair_drawoutline</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="視角與槍模-viewmodel" tabindex="-1"><a class="header-anchor" href="#視角與槍模-viewmodel"><span>視角與槍模 (Viewmodel)</span></a></h2>
<div class="language-cs line-numbers-mode" data-highlighter="shiki" data-ext="cs" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">viewmodel_presetpos</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">viewmodel_fov</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 63</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">viewmodel_offset_x</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 1.5</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">viewmodel_offset_y</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 2</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">viewmodel_offset_z</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> -</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">2</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="滑鼠靈敏度" tabindex="-1"><a class="header-anchor" href="#滑鼠靈敏度"><span>滑鼠靈敏度</span></a></h2>
<div class="language-cs line-numbers-mode" data-highlighter="shiki" data-ext="cs" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">sensitivity</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 2.00</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="音效設定" tabindex="-1"><a class="header-anchor" href="#音效設定"><span>音效設定</span></a></h2>
<div class="language-cs line-numbers-mode" data-highlighter="shiki" data-ext="cs" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">volume</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0.49</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">snd_headphone_eq</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 1</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">                  // 1 = Crisp 清晰</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="雷達與-hud-額外資訊" tabindex="-1"><a class="header-anchor" href="#雷達與-hud-額外資訊"><span>雷達與 HUD 額外資訊</span></a></h2>
<div class="language-cs line-numbers-mode" data-highlighter="shiki" data-ext="cs" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_allow_animated_avatars</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_radar_always_centered</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_radar_scale</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0.4</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_hud_telemetry_frametime_show</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 3</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">r_show_build_info</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> false</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">cl_predict_kill_ragdolls</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> false</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="快捷鍵綁定" tabindex="-1"><a class="header-anchor" href="#快捷鍵綁定"><span>快捷鍵綁定</span></a></h2>
<div class="language-cs line-numbers-mode" data-highlighter="shiki" data-ext="cs" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">bind</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">n</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">slot10</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">bind</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">x</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">use weapon_healthshot</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">bind</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">mwheelup</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">+jump</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">bind</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">v</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">switchhands</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">bind</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">mouse5</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">+voicerecord</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">unbind</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">mouse4</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">unbind</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">h</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="儲存配置" tabindex="-1"><a class="header-anchor" href="#儲存配置"><span>儲存配置</span></a></h2>
<div class="language-cs line-numbers-mode" data-highlighter="shiki" data-ext="cs" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">host_writeconfig</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="📚-下載資料" tabindex="-1"><a class="header-anchor" href="#📚-下載資料"><span>📚 下載資料</span></a></h2>
<p><a href="/downloads/autoexec.txt">下載設定檔</a> (需自行改副檔名)</p>
<div class="hint-container warning">
<p class="hint-container-title">注意</p>
<p>請下載後將副檔名由 .txt 改為 .cfg，以套用至遊戲內。</p>
</div>
</div></template>


